#ifndef G_0_DEBUG_SHORTCUT_H
#define G_0_DEBUG_SHORTCUT_H

#include "debug_types.h"

#define G_P0 G_0_DEBUG_FUNCTION_PARAMETER_PRELUDE0
#define G_P G_0_DEBUG_FUNCTION_PARAMETER_PRELUDE

#define G_RB G_0_DEBUG_ROOT_FUNCTION_BODY_PRELUDE
#define G_B G_0_DEBUG_FUNCTION_BODY_PRELUDE

#define G_A0 G_0_DEBUG_FUNCTION_ARGUMENT_PRELUDE0
#define G_A G_0_DEBUG_FUNCTION_ARGUMENT_PRELUDE

#endif
